services:
  # Static Site
  - type: web
    name: playgrowlb
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    autoDeploy: true
    
    # Environment Variables
    envVars:
      - key: VITE_API_URL
        value: https://growluckyblocks-tfpd.onrender.com
