-- Grow Lucky Blocks - Seed Data
-- Public servers are created in-memory by the game server (public-1..public-3)
-- and do not need database rows. Private servers are stored in the servers table
-- when players create them. No seed data is required.
